ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.example.presentation.config.KoinKt.configureKoin
      com.example.presentation.config.ValidationKt.configureValidation
      com.example.presentation.config.LoggingKt.configureCallLogging
      com.example.ResourcesKt.configureResources
      com.example.presentation.config.StatusPagesKt.configureStatusPages
      com.example.presentation.config.RoutingKt.configureRouting
      com.example.presentation.config.SerializationKt.configureSerialization
    ]
  }
}